### ISSUE TITLE
Problem when packing

### ISSUE THREAD

**Issue by Keblinger** [panzi/u4pak#10]
I got an error that said
`MacBook-Air:Paks sssss$ python u4pak.py pack Jack.pak out/`
`'ascii' codec can't decode byte 0xef in position 59: ordinal not in range(128)`

Can you help me resolve this problem?

**Comment by panzi** [comment]
Without looking at it more closely I think that means you use a filename that contains a non-ASCII character. IIRC I don't know what kind of encoding this archive format expects, so I only allow ASCII characters, just to be sure to not create a corrupted file.
