### ISSUE TITLE
Unsupported version: 7

### ISSUE THREAD

**Issue by kooz123** [panzi/u4pak#16]
Hey,

just trying to unpack some Fortnite paks, and got this output: 

`Evans-MacBook-Pro:u4pak-master evan$ ./u4pak.py list /Users/Shared/Epic\ Games/Fortnite/FortniteGame/Content/Paks/pakchunk0-MacClient.pak 
unsupported version: 7`

any help would be much appreciated

**Comment by panzi** [comment]
That means that that game uses version 7 of the file format. I only found descriptions of version 1 to 3 of the file format.

**Comment by panzi** [comment]
Same answer, sorry.

**Comment by panzi** [comment]
This version is supported now by this script. :D
