### ISSUE TITLE
Corrupted animations files

### ISSUE THREAD

**Issue by koMah** [panzi/u4pak#2]
When decompress a pak file, corrupted files are extracted (Skeletal Meshes, Animations)

UE4.7

**Comment by panzi** [comment]
Yeah, I only tested the UE4 Linux demos and those work. u4pack does not support compressed or encrypted archives. If you can debug and fix it I would pull any merge request. I literally don't know more than is written in README.md (first I reverse engineered parts of the archive format before someone else sent me their reverse engineering results that filled in a lot of blanks).
