### ISSUE TITLE
Unpacking error

### ISSUE THREAD

**Issue by Waaterbottle** [panzi/u4pak#20]
Hi i'm using cmd to run the script but i keep getting an error. " Illegal file magic: 0xc9ab0752" anything i'm doing wrong?

**Comment by panzi** [comment]
That means you try to use this script on a file that has an unsupported format (is not an Unreal engine 4 package as I know it).

**Comment by Waaterbottle** [comment]
Obviously not i was trying to open a developer tool not a texture pack *facepalm* thank you
