### ISSUE TITLE
unsupported version: 5

### ISSUE THREAD

**Issue by Token713** [panzi/u4pak#22]
whii

**Comment by panzi** [comment]
The Unreal Engine 4 package format has itself different versions. Each version adds some fields, so I can only correctly parse versions that I know. I don't have any descriptions on the package format in version 5.

**Comment by Keeperv85** [comment]
I think the v5 could match the v3 version structurally. The pack/uncpak process has not been tested yet, but the list function works. Try it, it might work!

**Comment by Technoguyfication** [comment]
I was able to successfully unpack a version 5 file using version 3. Can confirm this works!

**Comment by panzi** [comment]
Good to know!
