### ISSUE TITLE
error when unpacking

### ISSUE THREAD

**Issue by An0nymo0se** [panzi/u4pak#24]
when I use the "unpack" command, it gives me this error
 `illegal file magic: 0x00000000`
Is there something corrupted with my .pak file? 
![error](https://user-images.githubusercontent.com/49597455/56088769-f64f8a00-5e3b-11e9-99c1-2962a35ec83d.png)

**Comment by panzi** [comment]
Looks like the file is damaged or not a Unreal Engine 4 package format.

**Comment by fcoulombe** [comment]
I get the same error on windows and i can guarantee you that it's an unreal engine 4 pak file. I'm loading it with the game.

**Comment by panzi** [comment]
I've added an option `--ignore-magic`. Try that. Maybe it works by simply ignoring the file magic, maybe it will just crash in a more obscure way.

**Comment by NoTeefy** [comment]
@Panzi got the exact same problem with a UE4 .pak. It throws the same error and say "Unsupported version: 0" when trying it with ``--ignore-magic``

**Comment by panzi** [comment]
"version" 0? Wow. Well I guess it is just zeroing out these fields because the game knows the correct values, but a third party tool like this won't be able to understand it now. I might add an argument `--force-version=1` or so and you can try any supported versions until the script won't crash/won't produce broken output.

**Comment by NoTeefy** [comment]
Doesn't seem to solve my issue but thanks for the implementation. Gonna work on an own extractor 👍

**Comment by panzi** [comment]
I wonder, have you built your own extractor? Does it work?

**Comment by watchakorn-18k** [comment]
[https://media.discordapp.net/attachments/692263962204700675/846034657665089586/unknown.png](url)
i have problem

**Comment by panzi** [comment]
@watchakorn-18k That means that's not an Unreal Engine 4 pak file.
