### ISSUE TITLE
Nothing happens when unpacking a 4.22 pak file

### ISSUE THREAD

**Issue by GamingMidi** [panzi/u4pak#26]
When i try to unpack this pak file thats from a game in the unreal engine version 4.22... It does nothing at all, doesn't even give me an error.

**Comment by panzi** [comment]
That's weird. What is the exact command your typing? What is the path of the pak? What is your current directory, and what is any output you see in the terminal?

**Comment by GamingMidi** [comment]
Here's what cmd looks like when i try:
C:\Users\GamingMidi\Documents\Hello Neighbor Prototype Play At Your Own
Risk\HelloNeighbour\HelloNeighbour\Content\Paks\>u4pak.py
unpack HelloNeighbour-WindowsNoEditor.pak

C:\Users\GamingMidi\Documents\Hello Neighbor Prototype Play At Your Own
Risk\HelloNeighbour\HelloNeighbour\Content\Paks\>


and with an older version of u4pak that is compiled into an exe:
C:\Users\GamingMidi\Documents\Hello Neighbor Prototype Play At Your Own
Risk\HelloNeighbour\HelloNeighbour\Content\Paks\>u4pak.exe unpack
HelloNeighbour-WindowsNoEditor.pak
illegal file magic: 0x00000000

C:\Users\GamingMidi\Documents\Hello Neighbor Prototype Play At Your Own
Risk\HelloNeighbour\HelloNeighbour\Content\Paks>

**Comment by panzi** [comment]
What do you get when passing `--verbose`?

**Comment by GamingMidi** [comment]
--verbose?

**Comment by panzi** [comment]
```bash
u4pak.py unpack --verbose HelloNeighbour-WindowsNoEditor.pak 
```

**Comment by GamingMidi** [comment]
[image: image.png]

**Comment by panzi** [comment]
You can't post images on GitHub by send am email with an image attached. You need to upload it somewhere else and then link it.
