### ISSUE TITLE
New .pak version 4

### ISSUE THREAD

**Issue by TTimo** [panzi/u4pak#3]
UE4 has bumped the version number on their pak files. It is now at version 4. It's in UE4 4.17, not sure if it happened sooner than that. The script will abort on these new paks.

**Comment by panzi** [comment]
Did there anything change in the file format that requires the script to be adapted?

**Comment by TTimo** [comment]
(haven't checked yet .. just posting this in case someone's already on the case .. might be a few days)

**Comment by r-lyeh** [comment]
FYI, I've just checked against v4, and current code seems to list & unpack files for now.
Havent tested in depth.
Ty :)

```python
	elif version == 4:
		read_record = read_record_v3
```

**Comment by GeneralBison** [comment]
I get "unsupported version: 4" when trying to run the script against the .pak file from the game Ruiner.

**Comment by makc-ar** [comment]
How about Hidden Dragon Legend .pak http://store.steampowered.com/app/680390/Hidden_Dragon_Legend?
**script message::**
`decompression is not implemented yet`

**Comment by regret** [comment]
I am also getting 

"decompression is not implemented yet" error

**Comment by panzi** [comment]
Well, it'S not implemented, sorry. I don't have enough info to know how to implement it.

**Comment by huochai67** [comment]
i write 
```
elif version == 4:
read_record = read_record_v3
```
in u4pak.py,but i get a error 

> decompression is not implemented yet

Repair it,please

**Comment by panzi** [comment]
That's nothing to repair. It's a feature that's not implemented. I don't even have a pak that uses compression so I couldn't test and I don't know how to implement that anyway. If you want to contribute a patch: I accept pull requests.

**Comment by panzi** [comment]
Decompression is now implemented.
