### ISSUE TITLE
Can't even list files on 4.21 

### ISSUE THREAD

**Issue by megapro17** [panzi/u4pak#30]
```
python u4pak.py list "D:\Games\The Outer Worlds\Indiana\Content\Paks\pakchunk0-WindowsNoEditor.pak"
illegal file magic: 0x00000000

python u4pak.py list "D:\Games\The Outer Worlds\Indiana\Content\Paks\pakchunk0-WindowsNoEditor.pak" --ignore-magic
unsupported version: 0

python u4pak.py unpack "D:\Games\The Outer Worlds\Indiana\Content\Paks\pakchunk0-WindowsNoEditor.pak" --ignore-magic --force-version=1
```
And nothing... The game is definitely 4.21 version, as written in .exe description.

**Comment by panzi** [comment]
The version here is not about the game or Unreal engine version, but about the file format version. Hm. If I'm right it seems like more and more games try to obfuscate the archives and zero-out important parts of the file (because the game knows them anyway). Dunno how to handle that.

**Comment by megapro17** [comment]
> The version here is not about the game or Unreal engine version, but about the file format version. Hm. If I'm right it seems like more and more games try to obfuscate the archives and zero-out important parts of the file (because the game knows them anyway). Dunno how to handle that.

Dann. Even unrealpak.exe can't handle this:

```
D:\Games\Epic Games\UE_4.21\.egstore\bps\Install\Engine\Binaries\Win64>unrealpak.exe -List "D:\Games\The Outer Worlds\Indiana\Content\Paks\pakchunk0-WindowsNoEditor.pak"
LogPakFile: Display: Using command line for crypto configuration
LogWindows: Error: === Critical error: ===
LogWindows: Error:
LogWindows: Error: Fatal error: [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\PakFile\Private\IPlatformFilePak.cpp] [Line: 4054] LogWindows: Error: Trailing magic number (0d) in 'D:\Games\The Outer Worlds\Indiana\Content\Paks\pakchunk0-WindowsNoEditor.pak' is different than the expected one. Verify your installation.
```
So there is no easy method to open this file?

**Comment by panzi** [comment]
Is unrealpak.exe an official Unreal engine tool? I never actually used Unreal engine.

Anyway, you could try to add this on line 797:

```Python
	entry_count = 100
```
Note that it's important that the indentation is exactly one tab (not spaces). 100 is just a guess on file numbers, which means it will either not output all files or crash if there are fewer files than that. You can play around until you find the largest number that works. You will likely need to play around with different `--force-version` parameters too. Maybe try `--force-version=4`.

But if they go to this length they will probably also use encryption. The Unreal engine 4 archive format supports encryption, but this script does not. Even if it would you would need to get the encryption key from somewhere (probably somewhere hidden in the game exe).

Personally I don't get all these obfuscation and encryption measures. Don't they want mods that extend the lifetime of their game?

**Comment by megapro17** [comment]
I think, you mean line 827, after 
`entry_count = st_unpack('<I', stream.read(4))[0]`

I tried a lot of values, non of them are working...  Also added '--encoding=iso-8859-1', it just crashes with 'struct.error: unpack requires a buffer of 33855470992 bytes'...

**Comment by panzi** [comment]
Strange that it has a different line number for you. Sure you got the current version?

![](https://i.imgur.com/k9oJ1HI.png)

Also be sure not to *delete* the line containing the `stream.read(4)`. Have you tried with different values for `--force-version` and tried with a tiny `entry_count` value? What line has the buffer size error?

**Comment by megapro17** [comment]
I redownloaded the file, and it seems fine now
![image](https://user-images.githubusercontent.com/16743370/67803152-77e7cc00-fa9d-11e9-880d-b220ff40ace7.png)

With different `entry_count` it just throw `'utf-8' codec can't decode byte 0x90 in position 13: invalid start byte`
Then I added `--encoding=iso-8859-1` and it just eats all of my 16 gb ram. I selected smaller pak (2 mb only) file from same game and it shows this:
```
C:\Users\megapro17\AppData\Local\Programs\Python\Python37\python.exe "u4pak.py" list "D:\Games\The Outer Worlds\Indiana\Content\Paks\RU-WindowsNoEditor.pak" --ignore-magic --force-version=4 --encoding=iso-8859-1
Traceback (most recent call last):
  File "u4pak.py", line 1734, in <module>
    main(sys.argv[1:])
  File "u4pak.py", line 1616, in main
    pak = read_index(stream, args.check_integrity, args.ignore_magic, args.encoding, args.force_version)
  File "u4pak.py", line 804, in read_index
    record   = read_record(stream, filename)
  File "u4pak.py", line 578, in read_record_v4
    blocks = st_unpack('<%dQ' % (block_count * 2), stream.read(16 * block_count))
struct.error: unpack requires a buffer of 8721598400 bytes
```
Also tried different `entry_count`, not luck
> Have you tried with different values for --force-version and tried with a tiny entry_count value?
Yes, I tried, seems no effect at all

**Comment by panzi** [comment]
While reverse engineering archive files is fun to me and I do wonder how the files you want to extract are different to what the script currently supports I don't have much time for that right now **and** you shouldn't send me files if it would violate copyright.
