### ISSUE TITLE
UE4 pc - gears 5

### ISSUE THREAD

**Issue by by-freon** [panzi/u4pak#31]
Gears 5 uses oodle compression for b2container.
The GearGame.b2index file contains information about B2 container names, file names, and their location and size in b2containers.
There should be localization texts in Launch.b2container.
Could you please create a script at least to extract the files?
https://drive.google.com/open?id=18KaNNwO784lLA3g5X6ZGS0m3CAF78hxF

**Comment by Simo311** [comment]
I really wish someone could help with this...
