### ISSUE TITLE
Can't pack

### ISSUE THREAD

**Issue by JavierBlacksmith** [panzi/u4pak#35]
Hi, thanks and sorry for this noob issue.
Im trying to pack with a .bat that reads: u4pak.py pack jollyrogerf18.pak Nimbus
All three files in the same folder (Nimbus (folder), repack.bat and u4pak.py)

I was expecting it to spit a pak file named jollyrogerf18.pak, but it briefly opens a black window and then closes with no results.

Am I missing something?
I'm on windows, installed python 3.8.3 and 3.7.3, 
Tried with the .dds files I wanted to replace and also with an empty folder, also with different names and different directories, with no success. :(

**Comment by panzi** [comment]
Add this line at the end of the .bat file to keep the window open and look at the output.

     set /p DUMMY=Hit ENTER to continue...


Do you have Python installed? Hm, I guess under Windows you need to run it like this:

     C:\path\to\python.exe u4pak.py pack jollyrogerf18.pak Nimbus

It's just a Python script, not a stand alone program.

	-Mathias

**Comment by JavierBlacksmith** [comment]
Right, I was able to see the window and the error was that u4pak.py was not recognized, so I added my python location at the start, and it worked!
Thanks Mathias!

**Comment by CoIyn** [comment]
hello there, I am having the same issue, I was wondering if you could share what all you typed in your command line to get it working, thanks

**Comment by CoIyn** [comment]
just to add to my issue at hand I am currently attempting to pack the file (I am on windows 10) and I as well get the pop up for a moment and no file is produced. 
I have attempted the C:/python27>python.exe u4pak.py pack BGM_CHARA_003.pak MVCI
but I haven't gotten anything yet :l
