### ISSUE TITLE
How can I unpak?

### ISSUE THREAD

**Issue by NoxyOk** [panzi/u4pak#36]
Sorry for this noob issue, but I want to unpak some Fortnite Pak Files, how can I do?

**Comment by panzi** [comment]
Run:

```
python u4pak.py unpack C:\path\to\PakFile
```

In case Fortnite uses a pak version supported by my script.

Just google "run Python script under Windows" if you don't know how to do that.

**Comment by NoxyOk** [comment]
But I can't edit the u4pak.py file
