### ISSUE TITLE
checksum missmatch

### ISSUE THREAD

**Issue by kuyin** [panzi/u4pak#38]
<archive index>: checksum missmatch:
        got:      da39a3ee5e6b4b0d3255bfef95601890afd80709
        expected: 0000000000000000000000000000000000000000
Found 1 error(s)

What is the problem? And what should I do? Thanks!

**Comment by panzi** [comment]
Are you passing the `--test-integrity` argument? If yes try not doing that. The checksum in the archive seems to be nulled.

**Comment by panzi** [comment]
Btw. I just now renamed `--test-integrity` to `--check-integrity` (because I felt like it) and also added an option `--ignore-null-checksums`. So you still can do *some* metadata integrity checks even if the checksums are nulled.
