### ISSUE TITLE
Logic error in integrity check regarding compression = NONE

### ISSUE THREAD

**Issue by khadoran** [panzi/u4pak#39]
The check for mismatching compressed/uncompressed size is done when the data actually is compressed (r1.compression_method != COMPR_NONE):

Line 262: if r1.compression_method != COMPR_NONE and r1.compressed_size != r1.uncompressed_size:

this should be: if r1.compression_method == COMPR_NONE ...

**Comment by panzi** [comment]
You're right! Thank you! :D
