### ISSUE TITLE
Unreal Engine 3?

### ISSUE THREAD

**Issue by MoeMachine1** [panzi/u4pak#4]
Hello Panzi. I am huge fan of your work. I am wondering if there is a UE3 compatible version?
I am very interested in modding one of my favorite games now that Online support has been cut off and I cant reach one of the unlockables without switching out the files which is what I'd need u3pak for.

**Comment by panzi** [comment]
Currently I don't have any game that uses Unreal Engine 3 (because that engine doesn't support Linux). I wouldn't have much time for it right now anyway.
