### ISSUE TITLE
Variable referenced before assignment error in latest version

### ISSUE THREAD

**Issue by agc93** [panzi/u4pak#44]
When attempting to build a pack using `u4pak pack` with the latest version, I get the following error:

    `UnboundLocalError: local variable 'data' referenced before assignment`

From what I can tell, it's coming from [this line](https://github.com/panzi/u4pak/blob/master/u4pak.py#L677) where I _think_ `len(data)` should be `len(opt_data)`?

Complete stack trace below, happy to provide any other required details.

```text
Traceback (most recent call last):
  File "u4pak.py", line 1860, in <module>
    main(sys.argv[1:])
  File "u4pak.py", line 1807, in main
    callback=pack_callback, encoding=args.encoding)
  File "u4pak.py", line 951, in pack
    record = write_record(stream, fh, compression_method, encrypted, compression_block_size)
  File "u4pak.py", line 841, in write_record_v3
    compressed_size, sha1 = write_data(archive,fh,size,compression_method,encrypted,compression_block_size)
  File "u4pak.py", line 677, in write_data
    n = len(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by panzi** [comment]
Oh damn, your right. Thank you! Type checking with mypy is really lacking, sadly.
