### ISSUE TITLE
How to pack it again to .pak file i decrypt it now its a lot of .dat file i change some value but now i am not able to repack it

### ISSUE THREAD

**Issue by itsSwArchitect** [panzi/u4pak#49]

**Comment by panzi** [comment]
`u4pak.py pack NewArchive.pak --version=... --mount-point=... File1 File2...`
Version and mount point have to be like in the original archive. If you want to include all files from a directory but don't want it to be actually a directory in the archive you can do:
`u4pak.py pack NewArchive.pak --version=... --mount-point=... :rename=/:Path/To/Directory`

**Comment by panzi** [comment]
Wait, sorry, I was talking about the new https://github.com/panzi/rust-u4pak
That new version has the new rename feature and should be faster.

**Comment by itsSwArchitect** [comment]
> `u4pak.py pack NewArchive.pak --version=... --mount-point=... File1 File2...`
> Version and mount point have to be like in the original archive. If you want to include all files from a directory but don't want it to be actually a directory in the archive you can do:
> `u4pak.py pack NewArchive.pak --version=... --mount-point=... :rename=/:Path/To/Directory`

much much appreciated its a lot helpful for new programmers  Thanks you panzi
