### ISSUE TITLE
Errno 13 while trying to unpack

### ISSUE THREAD

**Issue by Maj-ew** [panzi/u4pak#52]
So I run Powershell inside folder with one .pak file that I try to unpack
Then I write "cmd" in powershell then "u4pak.exe unpack foldername" foldername is an existing folder next to .pak file.
And errno 13 occurs and it says "Permission denied: 'foldername'. What am I doing wrong. What can I do about it.
I tried in cmd too and the same thing happend when I just wrote "u4pak.exe list D:\games\originalpak" the directory is where the u4pak.exe is and my .pak file too
I have to mention that I run cmd and powershell as admin

Also have to mention that I don't have installed python which nobody ever tell that you have to install it to use .py files but anyway I was not using .py but .exe so it shouldn't be a thing I guess

**Comment by Maj-ew** [comment]
ok managed to just install the python and run my first .py somehow, even though all these tutorials are super inaccurate.
but you can close this thread after you red about the issue I had with the .exe version

**Comment by panzi** [comment]
Ok. Just wanted to mention that I wrote another version of that which has Windows binaries, so no Python needed. It has slightly different command line arguments, though. But it also has a feature where you put the command line arguments into a file and pass that file to the program (e.g. drop it on it), so you don't need to do command line stuff if that is a problem to you as a Windows user.
https://github.com/panzi/rust-u4pak

**Comment by panzi** [comment]
PS: What .exe version are you talking about? Only the Rust version (that other repo that I've just linked) has an .exe version.

**Comment by Maj-ew** [comment]
u4pak_SFV.7z that is how the 7z is called but I need to find the link where I got it from, but from mega.nz

**Comment by Maj-ew** [comment]
https://mega.nz/file/sE4n1TaR#kE7cvzLPEku5gU5LZFn1z8EvXIvVco6s7t7iYgIDIt0 this thing exactly, I don't even remember where did I get it from

**Comment by panzi** [comment]
Yeah, that has nothing to do with me and looks very suspicious. I mean, all mega download links to .exe files are very suspicious to me!
