### ISSUE TITLE
[ASK] do you know about paks 10 version??

### ISSUE THREAD

**Issue by TUNBudi06** [panzi/u4pak#58]
So i want to know how work the paks 10 version.
Bcz if i search in the forum2 is always say
Paks 1-9
Paks 11

Then where the paks 10 version please help me

**Comment by panzi** [comment]
Sorry, no idea. Also have no time for this at the moment.

**Comment by TUNBudi06** [comment]
Ok,thanks

But do you know about zstd compression

**Comment by panzi** [comment]
I know that it exists.

**Comment by TUNBudi06** [comment]
Ok,then i dont know how to calculate the zsize,size

Bcz in my case pubg using multiple zstd compression and not encrypted
