### ISSUE TITLE
pack.bat and unpack.bat is missing 

### ISSUE THREAD

**Issue by wither735** [panzi/u4pak#61]
Hello, lately I was trying to import a costume “map” from Unreal Engine into a Fortnite Private server in the Tutorial Video the guy used u4pak but in his Folder was also a pack.bat file wich he used and an unpack.bat file. 
I was wondering from where he was getting that, but maybe the file was updated.

Here is the Video (Go to minute 11:20) https://youtu.be/iSTXDzXdEtA

**Comment by panzi** [comment]
He probably wrote that himself. I don't have any .bat files here.
Note: With help by someone else (Xenira) I also wrote another version of this that is probably faster and has more features. See: https://github.com/panzi/rust-u4pak
